version: '3'
services:
  node:
    image: node:12
    working_dir: /app
    volumes:
      - .:/app:delegated
  ruby:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app:delegated
